---
- name: Install Tor project GPG signing key.
  apt_key:
    state: present
    data: "{{ lookup('file', 'tor-signing-key.pub') }}"
  tags:
    - apt
    - tor

- name: Setup Tor apt repo.
  apt_repository:
    repo: deb {{ tor_repo_url }} {{ tor_repo_distro }} main
    state: present
  register: add_tor_apt_repo
  tags:
    - apt
    - tor

- name: Update apt cache.
  apt:
    update_cache: yes
  when: add_tor_apt_repo.changed

- name: Install Tor and Tor keyring packages.
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ tor_repo_pkgs }}"
  tags:
    - apt
    - tor

- name: Extract tor version
  shell: |
    apt-cache policy tor | sed -e 's/^\s*Installed:\ \(\S*\)/\1/g;tx;d;:x'
  changed_when: false
  register: extract_tor_version
  when: "'amazon' in ansible_product_version"

- name: Dump Tor version to file (for reporting)
  copy:
    dest: "{{ playbook_dir }}/../../.tor_version"
    content: "{{ extract_tor_version.stdout }}"
  delegate_to: localhost
  run_once: true
  become: "no"
  when: "'amazon' in ansible_product_version"
